apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # project 必须先于 appset 同步。否则，appset 引用的 project 会因不存在而导致应用无法 syncing
  - projects/rd-backend.yaml        # 后端应用域边界
  - projects/rd-frontend.yaml       # 前端应用域边界
  - projects/rd-algorithm.yaml      # 算法应用域边界
  - appsets/rd-backend.yaml         # 后端应用批量生成器，扫描 apps/rd-backend 目录按环境发散
