# v4
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - virtual-service.yaml
images:
  - name: app                                # 匹配 base 里名为 app 的容器镜像字段
    newTag: 1.20.3
patches:
  - target:                                 # 目标：base 里的 DestinationRule
      kind: DestinationRule
      name: reviews-dr
    patch: |-                               # 改动：host 的命名空间段改成当前 overlay 的命名空间
      - op: replace
        path: /spec/host
        value: reviews.dev.svc.cluster.local
