apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  type: ClusterIP
  selector:
    app: productpage
  ports:
    - name: http
      port: 9080
      targetPort: 9080
      protocol: TCP
