apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - virtual-service.yaml
patches:
  - target:
      kind: DestinationRule
      name: reviews
    patch: |-
      - op: replace
        path: /spec/host
        value: reviews.dev.svc.cluster.local
