apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - virtual-service.yaml
images:
  - name: docker.io/istio/examples-bookinfo-details-v1
    newTag: 1.20.2
patches:
  - target:
      kind: ScaledObject
      name: details
    patch: |-
      - op: replace
        path: /spec/triggers/0/metadata/query
        value: |
          sum(rate(istio_requests_total{destination_service=~"details.*", destination_service_namespace="dev", response_code=~"2..|3.."}[2m]))
  - target:
      kind: DestinationRule
      name: details
    patch: |-
      - op: replace
        path: /spec/host
        value: details.dev.svc.cluster.local
